### ISSUE TITLE
Util: is_aligned uses modulus

### ISSUE THREAD

**Issue by ghost** [MammaMiaTeam/NSMB-Code-Reference#6]
BRUH

**Comment by Ed-1T** [comment]
No one gonna fix this?
Fine.
Keep your **__aeabi_uidivmod**.

**Comment by TheGameratorT** [comment]
Do you need division.s? :>

**Comment by Ed-1T** [comment]
no lol :trollface:

**Comment by TheGameratorT** [comment]
```cpp
bool is_aligned(int x)
{
    return (x & 3) == 0;
}
```
I will include this in my next commit.

**Comment by Ed-1T** [comment]
nice, that's the original code

**Comment by TheGameratorT** [comment]
Fixed in c21cf2c603f74bc327a50e3bb7b5bbc617852d98
