### ISSUE TITLE
BRUH rename int to long

### ISSUE THREAD

**Issue by ghost** [MammaMiaTeam/NSMB-Code-Reference#8]

**Comment by ghost** [comment]
no bruh don't
just change typedef from long to int loool kekw

**Comment by Ed-1T** [comment]
_this is fun_

**Comment by ghost** [comment]
:trollface:

**Comment by TheGameratorT** [comment]
@Overblade **BOLD**

**Comment by Ed-1T** [comment]
let me try markdown

# Nothing at all
![grandma_pc](https://user-images.githubusercontent.com/63556948/88484093-77b52800-cf6c-11ea-9c0f-66b5f5856b15.png)


[![forthebadge](https://forthebadge.com/images/badges/made-with-c-plus-plus.svg)](https://forthebadge.com)
[![forthebadge](https://forthebadge.com/images/badges/you-didnt-ask-for-this.svg)](https://forthebadge.com)

**Comment by ghost** [comment]
[![forthebadge](https://forthebadge.com/images/badges/powered-by-electricity.svg)](https://forthebadge.com)

**Comment by ItzTacosOfficial** [comment]
it seems to be really gay

**Comment by Ed-1T** [comment]
![rollsafe](https://user-images.githubusercontent.com/63556948/88484108-9f0bf500-cf6c-11ea-96f6-8db73a78a49a.png)

**Comment by ItzTacosOfficial** [comment]
![omegakek](https://user-images.githubusercontent.com/47322543/88484116-ad5a1100-cf6c-11ea-83af-4f4f8a05081f.png)

**Comment by Ed-1T** [comment]
this has become a meme channel

**Comment by ItzTacosOfficial** [comment]
![Tacochan](https://user-images.githubusercontent.com/47322543/88484122-bd71f080-cf6c-11ea-86ed-28c24e84ee29.png)

**Comment by Ed-1T** [comment]
![weirdchamp](https://user-images.githubusercontent.com/63556948/88484154-0033c880-cf6d-11ea-87c5-742118e7c64e.jpg)

issue is closed

**Comment by Ed-1T** [comment]
Hello! I just wanted to ask what you need an issue for. That's my puestion. 😃

also gj Grammarly for not fixing puestion, twice.
I'm about to remove it from chrome tho.

**Comment by ItzTacosOfficial** [comment]
are you sure that you are not gay?
